export type Difficulty = "easy" | "medium" | "hard";

export type QuestionType =
  | "mcq"
  | "assertion"
  | "case"
  | "numerical"
  | "concept"
  | "subjective";

export type TestMode =
  | "chapter"
  | "topic"
  | "full"
  | "weekly"
  | "board"
  | "pyq"
  | "revision";

export interface Chapter {
  id: string;
  name: string;
  nameHi?: string;
  topics: string[];
}

export interface Subject {
  id: string;
  name: string;
  nameHi?: string;
  icon: string; // emoji used in the UI
  chapters: Chapter[];
}

export interface ClassLevel {
  id: number; // 6..12
  /** subjects available for this class */
  subjects: Subject[];
}

export interface Question {
  id: string;
  classId: number;
  subjectId: string;
  chapterId: string;
  topic?: string;
  type: QuestionType;
  difficulty: Difficulty;
  marks: number;
  prompt: string;
  promptHi?: string;
  /** options for objective / assertion-reason questions */
  options?: string[];
  optionsHi?: string[];
  /** index into options for the correct choice (objective questions) */
  answerIndex?: number;
  /** model answer for subjective / numerical questions */
  answerText?: string;
  explanation?: string;
  explanationHi?: string;
  solutionSteps?: string[];
  /** Bihar Board exam years this PYQ appeared in (if any) */
  pyqYears?: number[];
  /** true for questions generated by the AI engine pending teacher review */
  aiSuggested?: boolean;
}

export const DIFFICULTIES: Difficulty[] = ["easy", "medium", "hard"];

export const QUESTION_TYPE_LABEL_KEY: Record<QuestionType, string> = {
  mcq: "qtMcq",
  assertion: "qtAssertion",
  case: "qtCase",
  numerical: "qtNumerical",
  concept: "qtConcept",
  subjective: "qtSubjective",
};

export const TEST_MODE_LABEL_KEY: Record<TestMode, string> = {
  chapter: "modeChapter",
  topic: "modeTopic",
  full: "modeFull",
  weekly: "modeWeekly",
  board: "modeBoard",
  pyq: "modePyq",
  revision: "modeRevision",
};
